/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ContactContent: typeof import('./src/components/content/ContactContent.vue')['default']
    Exercise: typeof import('./src/components/exerciseComponents/Exercise.vue')['default']
    ExerciseDetail: typeof import('./src/components/exerciseComponents/ExerciseDetail.vue')['default']
    ExerciseList: typeof import('./src/components/exerciseComponents/ExerciseList.vue')['default']
    ExerciseVisual: typeof import('./src/components/exerciseComponents/ExerciseVisual.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    PageContent: typeof import('./src/components/PageContent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Welkom: typeof import('./src/components/Welkom.vue')['default']
  }
}
