/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/account': RouteRecordInfo<'/account', '/account', Record<never, never>, Record<never, never>>,
    '/mijn-trainingen/': RouteRecordInfo<'/mijn-trainingen/', '/mijn-trainingen', Record<never, never>, Record<never, never>>,
    '/oefening-maken': RouteRecordInfo<'/oefening-maken', '/oefening-maken', Record<never, never>, Record<never, never>>,
    '/oefeningen/': RouteRecordInfo<'/oefeningen/', '/oefeningen', Record<never, never>, Record<never, never>>,
    '/oefeningen/[id]': RouteRecordInfo<'/oefeningen/[id]', '/oefeningen/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/training-maken/': RouteRecordInfo<'/training-maken/', '/training-maken', Record<never, never>, Record<never, never>>,
    '/training-maken/aanmaken': RouteRecordInfo<'/training-maken/aanmaken', '/training-maken/aanmaken', Record<never, never>, Record<never, never>>,
    '/trainingen/': RouteRecordInfo<'/trainingen/', '/trainingen', Record<never, never>, Record<never, never>>,
    '/trainingen/[id]': RouteRecordInfo<'/trainingen/[id]', '/trainingen/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
  }
}
